version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    # command: npm run start
    container_name: react_frontend_prod
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./:/frontend
      - /frontend/node_modules
  