version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/production/django/Dockerfile
    container_name: drf_taskmanager
    command: /start
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    # ports:
    #   - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
    environment:
      WAIT_HOSTS: db:5432
    networks:
      - taskmanager-django
  db:
    image: postgres:13.6-alpine
    restart: always 
    volumes:
      - postgres_taskmanager:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    networks:
      - taskmanager-django

networks:
  taskmanager-django:

volumes:
  postgres_taskmanager:
  static_volume:
  media_volume: